/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Language } from "./types";
import {
  TranslatedBook,
  ALL_66_BOOKS_METADATA,
  BIBLE_BOOKS,
  VERSES_OF_THE_DAY
} from "./fullBibleData";

export type { TranslatedBook };
export {
  ALL_66_BOOKS_METADATA,
  BIBLE_BOOKS,
  VERSES_OF_THE_DAY
};

export const I18N_DICTS: Record<Language, Record<string, string>> = {
  [Language.FR]: {
    appTitle: "BiblePro",
    tagline: "BiblePro – Votre compagnon spirituel intelligent optimal",
    home: "Accueil",
    bible: "La Bible",
    favorites: "Favoris",
    search: "Rechercher",
    settings: "Options",
    startReading: "Ouvrir les Saintes Écritures",
    verseOfTheDay: "Méditation Quotidienne",
    refreshVerse: "Nouveau Verset",
    globalStats: "Activité de Méditation",
    statVisits: "Nombres de visites",
    statVersesRead: "Versets parcourus",
    statFavorites: "Marque-pages sauvés",
    statLikes: "Mentions d'appréciations",
    explainWithAI: "Analyser avec BiblePro IA",
    explaining: "Analyse théologique en cours...",
    aiExplanation: "Explication Théologique",
    copy: "Copier le texte",
    copied: "Texte copié !",
    share: "Partager ce verset",
    shared: "Lien de partage copié !",
    downloadImage: "Convertir en Image 📸",
    noFavorites: "Aucun favori enregistré. Parcourez la Bible pour orner votre liste !",
    searchPlaceholder: "Saisir un mot-clé, thème ou passage biblique...",
    selectBook: "Sélectionner un livre saint",
    selectChapter: "Chapitre",
    allBooks: "Tous les livres canoniques",
    resultsFound: "verset(s) concordant(s) trouvé(s)",
    noResults: "Aucun résultat trouvé pour votre mot-clé de recherche.",
    animations: "Effets de transition",
    readAloud: "Lecture Audio (Synthèse Vocale)",
    autoScroll: "Défilement intelligent continu",
    autoScrollSpeed: "Vitesse (secondes par ligne)",
    language: "Changer de langue",
    langFR: "Français",
    langEN: "English",
    langSW: "Kiswahili",
    langRW: "Kinyarwanda",
    langES: "Español",
    focusMode: "Mode Lecture Pure (Plein écran)",
    footerText: "Copyright © Vab & Idriss (Vitech Africa) – Tous droits réservés",
    bibleNav: "Index de la Bible",
    explainTitle: "Explication de la Parole",
    close: "Fermer l'onglet",
    explainPrompt: "Donnez une belle perspective théologique de ce verset.",
    whatsAppShare: "Partager sur WhatsApp",
    facebookShare: "Partager sur Facebook",
    pwaAvailableScreens: "Disponible sur tous vos écrans",
    pwaDownloadTitle: "Télécharger BiblePro en 2 Sec",
    pwaDownloadDesc: "Profitez de l'application native autonome libre et optimisée. Sans passer par les magasins d'applications payants : notre icône Pro Max s'installe en arrière-plan et s'adapte à n'importe quel ordinateur, tablette ou smartphone.",
    pwaAndroidText: "💡 Android & Chrome: Cliquez sur le bouton de téléchargement ci-contre. Si le prompt est bloqué, ouvrez le menu de Chrome (trois petits points) et sélectionnez \"Installer l'application\" ou \"Ajouter à l'écran d'accueil\".",
    pwaIosText: "💡 iPhone / iPad iOS: Ouvrez cette page dans le navigateur Safari. Appuyez sur le bouton de partage bleu \"Partager\" (le carré avec une flèche vers le haut), faites défiler vers le bas et sélectionnez \"Sur l'écran d'accueil\".",
    pwaDesktopText: "💡 Windows & Mac Desktop: Cherchez l'icône de petit écran avec une flèche de téléchargement présente tout à droite de la barre d'adresse de votre navigateur Google Chrome ou Edge, cliquez dessus pour installer.",
    pwaInstalledText: "Déjà Installé !",
    pwaStandaloneMode: "Standalone Mode Activé",
    pwaDownloadButton: "Télécharger l'App",
    pwaCloudAddress: "Ouvrir l'adresse cloud",
    shareDivineWisdomTitle: "Partager la Divine Sagesse de l'Application",
    shareDivineWisdomDesc: "Choisissez l'un de nos messages persuasifs rédigés pour toucher le cœur et inciter vos amis à ouvrir l'application.",
    shareCountText: "Partages de Foi réalisés",
    sharePreviewTitle: "Aperçu de votre invitation Pro Max",
    copyMessageButton: "Copier le Message",
    sendMessageButton: "Envoyer / Partager",
    dbOfflineTitle: "Système de Base Globale Hors-ligne",
    dbOfflineDesc: "La BiblePro télécharge la totalité des livres et traductions directement dans le cache de votre appareil. Aucune connexion internet requise pour lire.",
    dbOnlineStatus: "Réseau Connecté",
    dbOnlineSubtitle: "Gemini IA active",
    dbOfflineStatus: "Mode Hors-ligne Actif",
    dbOfflineSubtitle: "Lecture de foi protégée",
    dbTranslations: "5 Traductions Complètes",
    dbBooksRead: "100% Intégralement pré-chargés",
    dbAiIntegration: "Gemini AI (Cache si disponible)",
    dbStorageUsed: "Stockage Utilisé",
    dbDiagnosticTitle: "Exécuter un contrôle d'intégralité locale",
    dbDiagnosticDesc: "Simule un rafraîchissement énergétique et teste la validité de tous les chapitres de foi de l'appareil.",
    dbDiagnosticButton: "Vérifier la base locale",
    dbDiagnosticChecking: "Analyse en cours...",
    dbDiagnosticSuccess: "✓ Tous les éléments bibliques locaux sont opérationnels à +100% ! Stockage optimisé. Vous pouvez couper votre réseau sereinement.",
    toastIntegritySuccessTitle: "Base de Données Locale Intacte ! 📖🔒",
    toastIntegritySuccessBody: "Les 66 livres bibliques, dictionnaires multilingues et répertoires de favoris ont été vérifiés avec succès et sont pré-chargés en mémoire tampon.",
    networkStatusConnectedTitle: "Statut Réseau : Connecté 🟢",
    networkStatusConnectedBody: "La BiblePro est synchronisée ! L'IA Gemini est pleinement opérationnelle.",
    networkStatusOfflineTitle: "Statut Réseau : Hors-ligne 🔴",
    networkStatusOfflineBody: "La BiblePro est passée en mode local sécurisé. Vos lectures restent 100% disponibles.",
    toastNativeShareSuccessTitle: "Union Sacrée ! 💕",
    toastNativeShareSuccessBody: "Merci d'avoir partagé la lumière spirituelle avec vos proches.",
    toastCopySuccessTitle: "Message copié avec succès ! 📜✨",
    toastCopySuccessBody: "Insérez-le sur WhatsApp, SMS, ou réseaux sociaux pour inspirer d'autres personnes.",
    toastDownloadSuccessTitle: "Téléchargement Réussi ! 📥",
    toastDownloadSuccessBody: "Le raccourci autonome 'BiblePro_Max.url' est enregistré dans vos Téléchargements. Ouvrez-le pour démarrer l'application instantanément.",
    toastPwaInstallSuccessTitle: "Bienvenue dans l'application BiblePro standalone ! 🎉",
    toastPwaInstallSuccessBody: "L'icône Pro Max a été installée avec succès sur votre bureau/écran d'accueil.",
    toastPwaInstallGuideTitle: "Guide d'installation",
    toastPwaInstallGuideBody: "Veuillez utiliser l'option de menu de votre navigateur (Ajouter à l'écran d'accueil)."
  },
  [Language.EN]: {
    appTitle: "BiblePro",
    tagline: "BiblePro – Your ultimate smart spiritual companion",
    home: "Home",
    bible: "The Bible",
    favorites: "Favorites",
    search: "Search",
    settings: "Settings",
    startReading: "Open Holy Scripture",
    verseOfTheDay: "Daily Meditation",
    refreshVerse: "Next Verse",
    globalStats: "Meditation Actions",
    statVisits: "Total study visits",
    statVersesRead: "Verses read",
    statFavorites: "Bookmarks saved",
    statLikes: "Verses liked",
    explainWithAI: "Explain with BiblePro AI",
    explaining: "Theological review in progress...",
    aiExplanation: "Theological Review",
    copy: "Copy text",
    copied: "Copied!",
    share: "Share verse",
    shared: "Link copied!",
    downloadImage: "Convert to Image 📸",
    noFavorites: "No bookmarks saved yet. Start browsing the Bible to add some!",
    searchPlaceholder: "Type keyword, passage reference, or topic...",
    selectBook: "Select standard book",
    selectChapter: "Chapter",
    allBooks: "All standard books",
    resultsFound: "matching verse(s) found",
    noResults: "No Bible passages matched your lookup keyword.",
    animations: "Visual transition effects",
    readAloud: "Speech Synthesis Reading",
    autoScroll: "Continuous Scroll",
    autoScrollSpeed: "Speed (seconds per line)",
    language: "International Language",
    langFR: "Français",
    langEN: "English",
    langSW: "Kiswahili",
    langRW: "Kinyarwanda",
    langES: "Español",
    focusMode: "Immersive View (Fullscreen)",
    footerText: "Copyright © Vab & Idriss (Vitech Africa) – All rights reserved",
    bibleNav: "Bible Index",
    explainTitle: "Scriptural Understanding",
    close: "Close Dialog",
    explainPrompt: "Provide a profound perspective for this scripture.",
    whatsAppShare: "Share on WhatsApp",
    facebookShare: "Share on Facebook",
    pwaAvailableScreens: "Available on all your screens",
    pwaDownloadTitle: "Download BiblePro in 2 Sec",
    pwaDownloadDesc: "Enjoy the optimized and free standalone native application. Without going through paid app stores: our Pro Max icon installs in the background and adapts to any computer, tablet, or smartphone.",
    pwaAndroidText: "💡 Android & Chrome: Click the download button on the right. If the prompt is blocked, open the Chrome menu (three dots) and select \"Install App\" or \"Add to Home Screen\".",
    pwaIosText: "💡 iPhone / iPad iOS: Open this page in Safari browser. Tap the blue \"Share\" button (square with arrow pointing up), scroll down and select \"Add to Home Screen\".",
    pwaDesktopText: "💡 Windows & Mac Desktop: Look for the small computer icon with a download arrow on the far right of the address bar in Google Chrome or Edge, click it to install.",
    pwaInstalledText: "Already Installed!",
    pwaStandaloneMode: "Standalone Mode Active",
    pwaDownloadButton: "Download App",
    pwaCloudAddress: "Open cloud address",
    shareDivineWisdomTitle: "Share the Divine Wisdom of the App",
    shareDivineWisdomDesc: "Choose one of our persuasive messages beautifully written to touch the heart and invite your friends to open the app.",
    shareCountText: "Shares of Faith completed",
    sharePreviewTitle: "Preview of your Pro Max invitation",
    copyMessageButton: "Copy Message",
    sendMessageButton: "Send / Share",
    dbOfflineTitle: "Global Offline Database System",
    dbOfflineDesc: "BiblePro downloads all books and translations directly onto your device cache. Zero internet connection required to read.",
    dbOnlineStatus: "Network Connected",
    dbOnlineSubtitle: "Gemini AI active",
    dbOfflineStatus: "Offline Mode Active",
    dbOfflineSubtitle: "Faith reading secured",
    dbTranslations: "5 Complete Translations",
    dbBooksRead: "100% Fully Preloaded",
    dbAiIntegration: "Gemini AI (Cached if available)",
    dbStorageUsed: "Storage Used",
    dbDiagnosticTitle: "Run a local integrity check",
    dbDiagnosticDesc: "Simulates an energetic refresh and tests the validity of all faith chapters on the device.",
    dbDiagnosticButton: "Verify Local Base",
    dbDiagnosticChecking: "Checking...",
    dbDiagnosticSuccess: "✓ All local Bible elements are +100% operational! Optimized storage. You can safely turn off your network.",
    toastIntegritySuccessTitle: "Local Database Intact! 📖🔒",
    toastIntegritySuccessBody: "All 66 scripture books, multilingual dictionaries, and bookmarks directories have been successfully verified and pre-buffered in memory.",
    networkStatusConnectedTitle: "Network Status: Connected 🟢",
    networkStatusConnectedBody: "BiblePro is fully synchronized! Gemini AI is operational.",
    networkStatusOfflineTitle: "Network Status: Offline 🔴",
    networkStatusOfflineBody: "BiblePro switched to secured local mode. Your reading sessions remain 100% available.",
    toastNativeShareSuccessTitle: "Sacred Union! 💕",
    toastNativeShareSuccessBody: "Thank you for sharing the spiritual light with your loved ones.",
    toastCopySuccessTitle: "Message successfully copied! 📜✨",
    toastCopySuccessBody: "Paste it on WhatsApp, SMS, or social networks to inspire others.",
    toastDownloadSuccessTitle: "Download Successful! 📥",
    toastDownloadSuccessBody: "The standalone desktop shortcut 'BiblePro_Max.url' has been downloaded. Open it to access the application instantly.",
    toastPwaInstallSuccessTitle: "Welcome to BiblePro standalone application! 🎉",
    toastPwaInstallSuccessBody: "The Pro Max icon has been successfully installed on your desktop/home screen.",
    toastPwaInstallGuideTitle: "Installation Guide",
    toastPwaInstallGuideBody: "Please use your browser menu options (Add to Home Screen)."
  },
  [Language.SW]: {
    appTitle: "BiblePro",
    tagline: "BiblePro – Mwongozo wako wa kiroho wa kila siku",
    home: "Mwanzo",
    bible: "Biblia",
    favorites: "Vipendwa",
    search: "Tafuta",
    settings: "Mipangilio",
    startReading: "Fungua Maandiko Matakatifu",
    verseOfTheDay: "Tafakari ya Siku",
    refreshVerse: "Aya Inayofuata",
    globalStats: "Utafiti wa Biblia",
    statVisits: "Wanaotembelea leo",
    statVersesRead: "Aya zilizosomwa",
    statFavorites: "Kalamuzi zilizowekwa",
    statLikes: "Alama za kupenda zilizopewa",
    explainWithAI: "Fafanua na BiblePro IA",
    explaining: "Uchambuzi wa kiteolojia unaendelea...",
    aiExplanation: "Uchambuzi wa Kiteolojia",
    copy: "Kiliandishi",
    copied: "Imetolewa nakala!",
    share: "Shirikisha aya",
    shared: "Kiungo cha kushiriki kimenakiliwa!",
    downloadImage: "Inua kuwa Picha 📸",
    noFavorites: "Hakuna alamisho zilizowekwa bado. Soma Biblia na uweke!",
    searchPlaceholder: "Andika neno la msingi, mada au aya...",
    selectBook: "Chagua kitabu cha Biblia",
    selectChapter: "Mlango",
    allBooks: "Vitabu vyote vya Biblia",
    resultsFound: "aya zilizopatikana",
    noResults: "Hakuna aya zilizopatikana kwa utafutaji wako.",
    animations: "Madhara ya mpito",
    readAloud: "Soma kwa sauti ya sauti (TTS)",
    autoScroll: "Usongezaji wa Moja kwa Moja",
    autoScrollSpeed: "Kasi (sekunde kwa kila aya)",
    language: "Badilisha Lugha",
    langFR: "Français",
    langEN: "English",
    langSW: "Kiswahili",
    langRW: "Kinyarwanda",
    langES: "Español",
    focusMode: "Njia ya Kusoma kwa Utulivu",
    footerText: "Hakimiliki zote ni za © Vab & Idriss (Vitech Africa) – Haki zote zimehifadhiwa",
    bibleNav: "Faharisi ya Biblia",
    explainTitle: "Ufafanuzi wa Neno la Mungu",
    close: "Funga Dirisha",
    explainPrompt: "Toa mtazamo mzuri wa kiteolojia kwa aya hii.",
    whatsAppShare: "Shiriki kwenye WhatsApp",
    facebookShare: "Shiriki kwenye Facebook",
    pwaAvailableScreens: "Inapatikana kwenye skrini zako zote",
    pwaDownloadTitle: "Pakua BiblePro kwa Sekunde 2",
    pwaDownloadDesc: "Furahia programu asili ya pekee na iliyoboreshwa bila malipo. Bila kupitia duka za programu zilizolipiwa: ikoni yetu ya Pro Max inasakinisha nyuma na inafaa kwa kompyuta, kompyuta kibao au simu yoyote.",
    pwaAndroidText: "💡 Android & Chrome: Bonyeza kitufe cha kupakua kulia. Kama ombi limezuiwa, fungua menyu ya Chrome (nukta tatu) na uchague \"Sakinisha programu\" au \"Ongeza kwenye skrini ya kwanza\".",
    pwaIosText: "💡 iPhone / iPad iOS: Fungua ukurasa huu kwenye kivinjari cha Safari. Gusa kitufe cha bluu cha \"Kushiriki\" (mraba wenye mshale unaoelekea juu), shuka chini na uchague \"Kwenye skrini ya kwanza\".",
    pwaDesktopText: "💡 Windows & Mac Desktop: Tafuta ikoni ya skrini ndogo yenye mshale wa kupakua upande wa kulia kabisa wa upau vya anwani kwenye kivinjari chako cha Chrome au Edge, kisha bofya ili kusakinisha.",
    pwaInstalledText: "Imesakinishwa Tayari!",
    pwaStandaloneMode: "Njia ya Standalone Imewezeshwa",
    pwaDownloadButton: "Pakua Programu",
    pwaCloudAddress: "Fungua anwani ya wingu",
    shareDivineWisdomTitle: "Shiriki Hekima ya Mungu ya Programu",
    shareDivineWisdomDesc: "Chagua moja ya ujumbe wetu mzuri ulioandikwa kugusa moyo na kualika marafiki zako kufungua programu.",
    shareCountText: "Mishiriki ya Imani iliyofanyika",
    sharePreviewTitle: "Angalia mwaliko wako wa Pro Max",
    copyMessageButton: "Nakili Ujumbe",
    sendMessageButton: "Tuma / Shiriki",
    dbOfflineTitle: "Mfumo vya Hifadhidata ya Nje ya Mtandao",
    dbOfflineDesc: "BiblePro inapakua vitabu na tafsiri zote moja kwa moja kwenye cache ya kifaa chako. Hakuna muunganisho wa mtandao unaohitajika kusoma.",
    dbOnlineStatus: "Mtandao Umeunganishwa",
    dbOnlineSubtitle: "Gemini AI inafanya kazi",
    dbOfflineStatus: "Njia ya Nje ya Mtandao Imefanya Kazi",
    dbOfflineSubtitle: "Kusoma kwa Imani kulindwa",
    dbTranslations: "Tafsiri 5 Kamili",
    dbBooksRead: "100% Imepakiwa Kamili",
    dbAiIntegration: "Gemini AI (Kache ikiwa inapatikana)",
    dbStorageUsed: "Nafasi Inayotumika",
    dbDiagnosticTitle: "Endesha uchunguzi wa uaminifu wa ndani",
    dbDiagnosticDesc: "Inatengeneza upya wa nguvu na kujaribu usahihi wa sura zote za imani kwenye kifaa.",
    dbDiagnosticButton: "Thibitisha Hifadhidata",
    dbDiagnosticChecking: "Uchambuzi unaendelea...",
    dbDiagnosticSuccess: "✓ Vipengele vyote vya Biblia ya ndani vinafanya kazi kwa +100%! Hifadhi iliyoboreshwa. Unaweza kuzima mtandao wako salama.",
    toastIntegritySuccessTitle: "Hifadhidata ya Ndani Iko Salama! 📖🔒",
    toastIntegritySuccessBody: "Vitabu vyote 66 vya maandiko, kamusi za lugha nyingi, na saraka za vipendwa vimethibitishwa kwa mafanikio na kuhifadhiwa kwenye kumbukumbu.",
    networkStatusConnectedTitle: "Hali ya Mtandao: Umeunganishwa 🟢",
    networkStatusConnectedBody: "BiblePro imesawazishwa kikamilifu! Gemini AI inafanya kazi.",
    networkStatusOfflineTitle: "Hali ya Mtandao: Nje ya Mtandao 🔴",
    networkStatusOfflineBody: "BiblePro imebadilika na kuwa modi ya usalama ya ndani. Vipindi vyako vya kusoma bado viko 100% kote.",
    toastNativeShareSuccessTitle: "Umoja wa Kiungu! 💕",
    toastNativeShareSuccessBody: "Asante kwa kushiriki nuru ya kiroho na wapendwa wako.",
    toastCopySuccessTitle: "Ujumbe umakiliwa kwa mafanikio! 📜✨",
    toastCopySuccessBody: "Ibandike kwenye WhatsApp, SMS, au mitandao ya kijamii ili kuhamasisha wengine.",
    toastDownloadSuccessTitle: "Upakuaji Umefanikiwa! 📥",
    toastDownloadSuccessBody: "Njia ya mkato ya pekee 'BiblePro_Max.url' imepakuliwa. Ifungue ili uingie kwenye programu wakati wowote mmoja.",
    toastPwaInstallSuccessTitle: "Karibu kwenye programu ya BiblePro ya pekee! 🎉",
    toastPwaInstallSuccessBody: "Ikoni ya Pro Max imesakinishwa kwa mafanikio kwenye kompyuta au skrini yako ya kwanza.",
    toastPwaInstallGuideTitle: "Mwongozo wa Usakinishaji",
    toastPwaInstallGuideBody: "Tafadhali tumia chaguo za menyu ya kivinjari chako (Ongeza kwenye skrini ya kwanza)."
  },
  [Language.RW]: {
    appTitle: "BiblePro",
    tagline: "BiblePro – Inshuti n'umuyobozi wawe mu mwuka wera",
    home: "Ahabanza",
    bible: "Bibiliya Yera",
    favorites: "Ibyatoranyijwe",
    search: "Gushakisha",
    settings: "Igenamiterere",
    startReading: "Fungura Ibyanditswe Byera",
    verseOfTheDay: "Gusoma ku munsi",
    refreshVerse: "Umurongo utaha",
    globalStats: "Umusaruro w'isomo",
    statVisits: "Abasuye bose hamwe",
    statVersesRead: "Imirongo yasomwe",
    statFavorites: "Ibimenyetso byabitswe",
    statLikes: "Indangagaciro gukunda",
    explainWithAI: "Sobanura muryo bwa BiblePro IA",
    explaining: "Ubusobanuzi bwa tewolojiya burimo...",
    aiExplanation: "Ubusobanuro bwa Tewolojiya",
    copy: "Koporora umurongo",
    copied: "Byakoporowe neza!",
    share: "Sangiza abandi binjiye",
    shared: "Ihuza ryo gusangiza ryabitswe!",
    downloadImage: "Shyira mu ishusho 📸",
    noFavorites: "Nta mirongo watoranyije urabona. Soma Bibiliya maze utoranye zimwe !",
    searchPlaceholder: "Andika izina ry'igitabo, igice cyangwa ijambo...",
    selectBook: "Hitamo igitabo cyanoneke",
    selectChapter: "Igice",
    allBooks: "Ibitabo byose byera cyane",
    resultsFound: "imirongo yabonetse",
    noResults: "Nta bisubizo byabonetse bihuye n'ijambo ryawe.",
    animations: "Uburyo amashusho anyuramo",
    readAloud: "Soma mu ijwi rya roba (Soma mu ijwi)",
    autoScroll: "Gusoma dusesa amasegonda",
    autoScrollSpeed: "Umuvuduko (amasegonda kuri buri murongo)",
    language: "Guhitamo Ururimi",
    langFR: "Français",
    langEN: "English",
    langSW: "Kiswahili",
    langRW: "Kinyarwanda",
    langES: "Español",
    focusMode: "Soma Imyanya yera yonyine",
    footerText: "Uburenganzira bwose ni ubwa © Vab & Idriss (Vitech Africa) – All rights reserved",
    bibleNav: "Inzira ya Bibiliya",
    explainTitle: "Kusobanukirwa n'Ijambo",
    close: "Funga icyiciro",
    explainPrompt: "Tanga ibisobanuro byiza kandi birambuye by'uyu murongo.",
    whatsAppShare: "Sangiza kuri WhatsApp",
    facebookShare: "Sangiza kuri Facebook",
    pwaAvailableScreens: "Iboneka kuri ecran zawe zose",
    pwaDownloadTitle: "Shyira BiblePro mu masegonda 2",
    pwaDownloadDesc: "Koresha porogaramu yigenga, ifite umuvuduko kandi y'ubuntu. Bitabaye ngombwa ko unyura mu maduka ya porogaramu yishurwa: agashushanyo kacu ka Pro Max kashyirwa inyuma kandi kagakora kuri mudasobwa, tabled cyangwa telefone yose.",
    pwaAndroidText: "💡 Android & Chrome: Kanda kuri buto yo gushyira kuri telefone. Ibyo bishatse gufungwa, fungura menu ya Chrome (utudomo dutatu) maze uhitemo \"Shyiraho porogaramu\" cyangwa \"Shyira ahabanza\".",
    pwaIosText: "💡 iPhone / iPad iOS: Fungura uyu mukoranyambaga muri Safari. Kanda buto y'ubururu yo \"Gusangiza\" (agasanduku karimo akamenyetso k'akambi kerekeza hejuru), umanuke hasi uhitemo \"Shyira ahabanza\".",
    pwaDesktopText: "💡 Windows & Mac Desktop: Shaka kamanyetso ka ecran ifite akambi kamanuka buryo bwa mudasobwa iburyo kuri Chrome cyangwa Edge, ukandyemo uyishyireho.",
    pwaInstalledText: "Yamaze gushyirwaho!",
    pwaStandaloneMode: "Uburyo bwigenga bwafunguwe",
    pwaDownloadButton: "Kura porogaramu",
    pwaCloudAddress: "Fungura aderesi ya cloud",
    shareDivineWisdomTitle: "Sangiza abandi Ubwenge bw'Imana bwa Porogaramu",
    shareDivineWisdomDesc: "Hitamo bumwe mu butumwa bwiza bwanditse neza kugira ngo buhumurize umutima maze usangize n'inshuti zawe gufungura porogaramu.",
    shareCountText: "Ibikorwa byo gusangiza bimaze gukorwa",
    sharePreviewTitle: "Ibyo ubutumwa bwa Pro Max bugiye kugaragaza",
    copyMessageButton: "Koporora Ubutumwa",
    sendMessageButton: "Ohereza / Sangiza",
    dbOfflineTitle: "Uburyo bwa database idakoresha interineti",
    dbOfflineDesc: "BiblePro yimanurira ibitabo n'ubuhinduzi byose muri telefone yawe. Ntakigo cya interineti gikenewe kugira ngo usome.",
    dbOnlineStatus: "Ihuza rya interineti rirakora",
    dbOnlineSubtitle: "Gemini AI irakora",
    dbOfflineStatus: "Modi idakoresha interineti irakora",
    dbOfflineSubtitle: "Gusoma mu kwizera kurarinzwe",
    dbTranslations: "Ubuhinduzi 5 bwuzuye",
    dbBooksRead: "100% Bishyizwe muri telefone neza",
    dbAiIntegration: "Gemini AI (Bibikwa iyo bihari)",
    dbStorageUsed: "Ububiko bukodoshwa",
    dbDiagnosticTitle: "Kora isuzuma ry'ubuziranenge bw'imbere",
    dbDiagnosticDesc: "Ihindura neza kandi isuzuma igice cyose cy'ibitabo byera biri kuri telefone yawe.",
    dbDiagnosticButton: "Saba isuzuma ry'imbere",
    dbDiagnosticChecking: "Isuzuma ririmo...",
    dbDiagnosticSuccess: "✓ Ibiranga Bibiliya byose by'imbere birakora neza ku kigereranyo cya +100%! Ububiko bwateguwe. Ushobora gufunga interineti utuje.",
    toastIntegritySuccessTitle: "Database y'Imbere ni Nziza! 📖🔒",
    toastIntegritySuccessBody: "Ibitabo 66 byera, inyandiko z'indimi nyinshi n'imitwe y'amasengesho byemejwe neza kandi bishyirwa mu bubiko bugufi.",
    networkStatusConnectedTitle: "Ihuza rya interineti: Rirakora 🟢",
    networkStatusConnectedBody: "BiblePro yajyanywe hamwe! Gemini AI irakora neza.",
    networkStatusOfflineTitle: "Ihuza rya interineti: Ntabwo ririmo 🔴",
    networkStatusOfflineBody: "BiblePro yinjiye mu buryo burinzwe bw'imbere. Gusoma kwawe birahari 100%.",
    toastNativeShareSuccessTitle: "Ubumwe bweranye! 💕",
    toastNativeShareSuccessBody: "Urakoze gusangiza uyu mucyo mu mutima w'abantu bawe.",
    toastCopySuccessTitle: "Byagendekeye neza bishyizwe mu bubiko! 📜✨",
    toastCopySuccessBody: "Yishyire kuri WhatsApp, SMS, cyangwa mbuga nkoranyambaga kugira ngo uhumurize abandi.",
    toastDownloadSuccessTitle: "Bimanutse neza! 📥",
    toastDownloadSuccessBody: "Inzira yihuse ya 'BiblePro_Max.url' ryamaze kumanuka. Lifungure kugira ngo winjire muri porogaramu igihe cyose.",
    toastPwaInstallSuccessTitle: "Murakaza neza muri porogaramu yigenga ya BiblePro! 🎉",
    toastPwaInstallSuccessBody: "Agashushanyo ka Pro Max kashyizwe neza cyane ahabanza cyangwa kuri ecran.",
    toastPwaInstallGuideTitle: "Inyoboragitabo yo gushyiraho",
    toastPwaInstallGuideBody: "Nyamuneka koresha ibikubiye mu menu y'umukoranyambaga wawe (Shyira kuri ecran ahabanza)."
  },
  [Language.ES]: {
    appTitle: "BiblePro",
    tagline: "BiblePro – Su compañero devocional sabio e inteligente",
    home: "Inicio",
    bible: "La Biblia",
    favorites: "Favoritos",
    search: "Buscador",
    settings: "Opciones",
    startReading: "Abrir las Sagradas Escrituras",
    verseOfTheDay: "Meditación Divina",
    refreshVerse: "Nuevo Versículo",
    globalStats: "Actividad de Estudio",
    statVisits: "Total visitas devocionales",
    statVersesRead: "Versículos leídos",
    statFavorites: "Marcadores guardados",
    statLikes: "Me gustas registrados",
    explainWithAI: "Interpretar con BiblePro IA",
    explaining: "Análisis teológico en curso...",
    aiExplanation: "Análisis Teológico",
    copy: "Copiar texto",
    copied: "¡Texto copiado!",
    share: "Compartir pasaje",
    shared: "¡Enlace copiado con éxito!",
    downloadImage: "Convertir en Imagen 📸",
    noFavorites: "No hay versículos en su lista devocional. ¡Lea la Biblia y añada alguno!",
    searchPlaceholder: "Escriba un tema de fe, número, o palabra clave...",
    selectBook: "Seleccione un libro canónico",
    selectChapter: "Capítulo",
    allBooks: "Todos los libros bíblicos",
    resultsFound: "versículo(s) coincidente(s) hallado(s)",
    noResults: "No se hallaron concordancias de fe para su búsqueda.",
    animations: "Efectos visuales dinámicos",
    readAloud: "Lectura de voz sintetizada",
    autoScroll: "Auto desplazamiento suave",
    autoScrollSpeed: "Velocidad (segundos por pasaje)",
    language: "Cambiar Idioma",
    langFR: "Français",
    langEN: "English",
    langSW: "Kiswahili",
    langRW: "Kinyarwanda",
    langES: "Español",
    focusMode: "Modo Enfoque Devocional (Imersivo)",
    footerText: "Derechos de autor © Vab & Idriss (Vitech Africa) – Todos los derechos reservados",
    bibleNav: "Navegación Bíblica",
    explainTitle: "Explicación Bíblica",
    close: "Cerrar Panel",
    explainPrompt: "De una interpretación constructiva y edificante de esta escritura.",
    whatsAppShare: "Compartir en WhatsApp",
    facebookShare: "Compartir en Facebook",
    pwaAvailableScreens: "Disponible en todas sus pantallas",
    pwaDownloadTitle: "Descargar BiblePro en 2 Seg",
    pwaDownloadDesc: "Disfrute de la aplicación nativa independiente gratuita y optimizada. Sin pasar por tiendas de aplicaciones de pago: nuestro icono Pro Max se instala en segundo plano y se adapta a cualquier ordenador, tableta o smartphone.",
    pwaAndroidText: "💡 Android & Chrome: Haga clic en el botón de descarga de la derecha. Si se bloquea el aviso, abra el menú de Chrome (tres puntos) y seleccione \"Instalar aplicación\" o \"Añadir a la pantalla de inicio\".",
    pwaIosText: "💡 iPhone / iPad iOS: Abra esta página en el navegador Safari. Presione el botón azul de \"Compartir\" (el cuadrado con la flecha hacia arriba), desplácese hacia abajo y seleccione \"Añadir a la pantalla de inicio\".",
    pwaDesktopText: "💡 Windows & Mac Desktop: Busque el icono de la pantalla pequeña con una flecha de descarga en el extremo derecho de la barra de direcciones de su navegador Google Chrome o Edge, haga clic en él para instalar.",
    pwaInstalledText: "¡Ya Instalado!",
    pwaStandaloneMode: "Modo Independiente Activo",
    pwaDownloadButton: "Descargar la App",
    pwaCloudAddress: "Abrir dirección cloud",
    shareDivineWisdomTitle: "Compartir la Sabiduría Divina de la App",
    shareDivineWisdomDesc: "Elija uno de nuestros mensajes persuasivos redactados para tocar el corazón e invitar a sus amigos a abrir la aplicación.",
    shareCountText: "Veces compartido con fe",
    sharePreviewTitle: "Vista previa de su invitación Pro Max",
    copyMessageButton: "Copiar Mensaje",
    sendMessageButton: "Enviar / Compartir",
    dbOfflineTitle: "Sistema Global de Base de Datos Offline",
    dbOfflineDesc: "BiblePro descarga la totalidad de los libros y traducciones directamente en la caché de su dispositivo. No se requiere conexión a internet para leer.",
    dbOnlineStatus: "Red Conectada",
    dbOnlineSubtitle: "IA Gemini activa",
    dbOfflineStatus: "Modo Offline Activo",
    dbOfflineSubtitle: "Lectura de fe protegida",
    dbTranslations: "5 Traducciones Completas",
    dbBooksRead: "100% Totalmente Precargados",
    dbAiIntegration: "IA Gemini (Caché si está disponible)",
    dbStorageUsed: "Almacenamiento Usado",
    dbDiagnosticTitle: "Ejecutar control de integridad local",
    dbDiagnosticDesc: "Simula una actualización energética y comprueba la validez de todos los capítulos de fe del dispositivo.",
    dbDiagnosticButton: "Verificar base local",
    dbDiagnosticChecking: "Comprobando...",
    dbDiagnosticSuccess: "✓ ¡Todos los elementos bíblicos locales están operativos al +100%! Almacenamiento optimizado. Puede apagar su red con total tranquilidad.",
    toastIntegritySuccessTitle: "¡Base de Datos Local Intacta! 📖🔒",
    toastIntegritySuccessBody: "Los 66 libros bíblicos, diccionarios multilingües y directorios de favoritos se han verificado con éxito y se han guardado en la memoria.",
    networkStatusConnectedTitle: "Estado de la Red: Conectado 🟢",
    networkStatusConnectedBody: "¡La BiblePro está sincronizada! El asistente IA está en pleno funcionamiento.",
    networkStatusOfflineTitle: "Estado de la Red: Offline 🔴",
    networkStatusOfflineBody: "La BiblePro ha pasado al modo local seguro. Sus lecturas de fe siguen estando 100% disponibles.",
    toastNativeShareSuccessTitle: "¡Unión Sagrada! 💕",
    toastNativeShareSuccessBody: "Gracias por compartir la luz espiritual con sus seres queridos.",
    toastCopySuccessTitle: "¡Mensaje copiado con éxito! 📜✨",
    toastCopySuccessBody: "Péguelo en WhatsApp, SMS o redes sociales para inspirar a otros.",
    toastDownloadSuccessTitle: "¡Descarga Exitosa! 📥",
    toastDownloadSuccessBody: "El acceso directo independiente 'BiblePro_Max.url' está en su carpeta de descargas. Ábralo para acceder a la app en cualquier momento.",
    toastPwaInstallSuccessTitle: "¡Bienvenido a la aplicación independiente BiblePro! 🎉",
    toastPwaInstallSuccessBody: "El icono de Pro Max se ha instalado correctamente en su escritorio/pantalla de inicio.",
    toastPwaInstallGuideTitle: "Guía de instalación",
    toastPwaInstallGuideBody: "Por favor use las opciones del menú de su navegador (Añadir a la pantalla de inicio)."
  }
};
